### ISSUE TITLE
avoid overfitting?

### ISSUE THREAD

**Issue by tlemberger** [Docmaps-Project/docmaps#1]
It might be useful to have at least 2 or more examples and platforms to start modeling in order to avoid unintentional overfitting :-) 

Here would be a few examples from the Early Evidence Base pilot:
- https://eeb.embo.org/doi/10.1101/2020.01.13.891630
- https://eeb.embo.org/doi/10.1101/2020.05.14.095968
- https://eeb.embo.org/doi/10.1101/2021.04.06.21254882

Some of these examples illustrate the sequential involvement of 2 reviewing services. This could be interesting for the initial model. The display is also different, emphasizing more on the concept of a whole peer-review process and perhaps less oriented on sequential 'events'. Finally, some are from author-driven submission systems while the last is from an author-independent platform.

**Comment by ships** [comment]
We currently have 5 examples going in the `examples/` directory, including some that disagree on exact usage. While we should always keep an eye on issues of overfitting to our samples and get stakeholders directly involved in getting their needs met.
