### ISSUE TITLE
Widget: When a ThingT is declared multiple times in the same docmap, the UI should show a union of all the attributes it has across all declarations

### ISSUE THREAD

**Issue by andrewedstrom** [Docmaps-Project/docmaps#171]
# Feature Request

Packages to improve:

- [ ] OWL/SHACL definitions
- [ ] ts-sdk
- [ ] ts-etl
- [ ] spa

### Description

Describe the new feature you would like to see added to the library.

### Use case

Describe how you plan to use this feature and why it is important to you.

### Proposed solution

If you have an idea for how this feature could be implemented, please describe it here.

### Additional information

Provide any additional information that might be helpful in understanding the feature request.

**Comment by ships** [comment]
Instinct: do this merging if the ThingT is declared by its ID in the source docmap, but NOT if it is declared by DOI .

Rationale: DOIs are only "mostly" unique identifiers. We could do some empirical studying to see whether the fields in question ever or often disagree and therefore would cause trouble.

Caveat: the ID in the docmap is "unique", but we can't force users to do this correctly. I.e., they can generate docmaps stupidly and I have some expectation that they will do so. Therefore the same complaint re: DOIs may apply.
