### ISSUE TITLE
"review_number" vs "runningNumber"

### ISSUE THREAD

**Issue by tlemberger** [Docmaps-Project/docmaps#4]
Crossref schema https://data.crossref.org/reports/help/schema_doc/4.4.2/index.html uses `running_number` to specify the order of referee reports within a round of pee review. I find it slightly clearer than`review_number` which could be misunderstood as related to the number of referee reports in a round of peer review.

(should all the attributes be in camel case ie `runningNumber`?)

**Comment by ships** [comment]
This pertains currently to extended usage of docmaps, rather than core protocol, so i will close the issue. EMBO is using `runningNumber` successfully, so i would say let's open a new issue if we want to promote that usage into core ontologies.
